google-gc-rs.pdf: google-gc-rs.tex google-gc-rs.bib
	pdflatex google-gc-rs.tex; bibtex google-gc-rs; pdflatex google-gc-rs.tex

attrs.pdf: attrs.tex attrs.bib
	pdflatex attrs.tex; bibtex attrs; pdflatex attrs.tex
	
rs.pdf: rs.tex rs.bib
	pdflatex rs.tex; bibtex rs; pdflatex rs.tex
